name: linter-and-tests
on: [ push ]
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: python install
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Change to backend directory, install poetry, and run commands
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: True
          DOCKER: False
        run: |
          cd backend
          pip install poetry
          poetry install
          poetry run python manage.py makemigrations
          make lint
          make test
